#
# docker build -t xpanda/nginx:0.0.1 .
#

FROM envoyproxy/envoy-build-centos:latest

MAINTAINER from xpanda.info by pauljoo (jianghuiyao@outlook.com)

ENTRYPOINT ["tail", "-F", "/dev/null"]
